#!/usr/bin/env python3
"""Automatic semantic version bump for GitHub Actions publish workflow."""

import os
import re
from pathlib import Path
from typing import Tuple

PYPROJECT_PATH = Path("pyproject.toml")
INIT_PATH = Path("amazon_creators_async_api/__init__.py")


def get_current_version() -> str:
    content = PYPROJECT_PATH.read_text(encoding="utf-8")
    match = re.search(r'version = "(\d+\.\d+\.\d+)"', content)
    if not match:
        raise RuntimeError("Could not find version in pyproject.toml")
    return match.group(1)


def parse_version(version: str) -> Tuple[int, int, int]:
    major, minor, patch = version.split(".")
    return int(major), int(minor), int(patch)


def format_version(major: int, minor: int, patch: int) -> str:
    return f"{major}.{minor}.{patch}"


def detect_bump_type(message: str) -> str:
    msg = (message or "").strip().lower()

    # Avoid release-loop commits generated by this workflow.
    if msg.startswith("chore(release):"):
        return "none"

    # Breaking change = MAJOR.
    # Handles both conventional "breaking change" / "feat!" and the
    # auto-PR title prefix generated by auto-pr.yml: "💥 breaking: ..."
    if "breaking change" in msg or "feat!" in msg or re.match(r"[^a-z]*breaking[:(]", msg):
        return "major"

    if re.match(r"feat[:(]", msg):
        return "minor"

    if re.match(r"(fix|refactor|perf)[:(]", msg):
        return "patch"

    # Default: publish a patch so every merge to master can ship.
    return "patch"


def bump_version(current: str, bump_type: str) -> str:
    if bump_type == "none":
        return current

    major, minor, patch = parse_version(current)

    if bump_type == "major":
        return format_version(major + 1, 0, 0)
    if bump_type == "minor":
        return format_version(major, minor + 1, 0)
    return format_version(major, minor, patch + 1)


def update_pyproject_version(new_version: str) -> None:
    content = PYPROJECT_PATH.read_text(encoding="utf-8")
    updated = re.sub(
        r'version = "\d+\.\d+\.\d+"',
        f'version = "{new_version}"',
        content,
        count=1,
    )
    PYPROJECT_PATH.write_text(updated, encoding="utf-8")


def update_init_version(new_version: str) -> None:
    content = INIT_PATH.read_text(encoding="utf-8")

    if re.search(r'__version__\s*=\s*"\d+\.\d+\.\d+"', content):
        updated = re.sub(
            r'__version__\s*=\s*"\d+\.\d+\.\d+"',
            f'__version__ = "{new_version}"',
            content,
            count=1,
        )
    else:
        updated = content.rstrip() + f"\n\n__version__ = \"{new_version}\"\n"

    INIT_PATH.write_text(updated, encoding="utf-8")


def write_outputs(version: str, should_publish: bool, bump_type: str) -> None:
    output_path = os.environ.get("GITHUB_OUTPUT")
    if not output_path:
        return

    with open(output_path, "a", encoding="utf-8") as out:
        out.write(f"version={version}\n")
        out.write(f"should_publish={'true' if should_publish else 'false'}\n")
        out.write(f"bump_type={bump_type}\n")


def main() -> None:
    commit_message = os.environ.get("GIT_COMMIT_MESSAGE", "")
    bump_type = detect_bump_type(commit_message)
    current_version = get_current_version()

    if bump_type == "none":
        write_outputs(current_version, False, bump_type)
        print(f"Skipping bump for commit message: {commit_message}")
        return

    new_version = bump_version(current_version, bump_type)
    update_pyproject_version(new_version)
    update_init_version(new_version)
    write_outputs(new_version, True, bump_type)

    print(f"Version bumped ({bump_type}): {current_version} -> {new_version}")


if __name__ == "__main__":
    main()
